line_length:
  warning: 300

type_body_length:
  warning: 500

file_length:
  warning: 750

disabled_rules:
  - trailing_whitespace
  - todo

type_name:
  allowed_symbols:
    - "_"
  excluded:
    - iOS_FakeNFT_ExtendedApp

identifier_name:
  excluded:
    - _placeholder
    - id

excluded:
  - .git
  - Pods
  - Carthage
