included:
  - iOS-FakeNFT-Extended
  - iOS-FakeNFT-ExtendedTests
  - iOS-FakeNFT-ExtendedUITests

excluded:
  - iOS-FakeNFT-Extended.xcodeproj
  - .build
  - .swiftpm
  - DerivedData

disabled_rules:
  - line_length
  - todo

identifier_name:
  excluded:
    - id
    - _placeholder

type_name:
  excluded:
    - iOS_FakeNFT_ExtendedApp