included:
  - iOS-FakeNFT-Extended
  - iOS-FakeNFT-ExtendedTests
  - iOS-FakeNFT-ExtendedUITests

excluded:
  - iOS-FakeNFT-Extended.xcodeproj
  - .build
  - .swiftpm
  - DerivedData

disabled_rules:
  - line_length
  - todo
  - trailing_whitespace

identifier_name:
  excluded:
    - id
    - vm
    - _placeholder

type_name:
  allowed_symbols:
    - "_"
  excluded:
    - iOS_FakeNFT_ExtendedApp
